routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('homepage');

//asset category route

Route::resource('categories', 'CategoryController');
//assets routes

Route::resource('assets', 'AssetController');
//roles routes

Route::resource('roles', 'RoleController');
//users routes

Route::resource('users', 'UserController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role() 
    {
        return $this->belongsTo(Role::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use App\User;
use App\Role;
use Illuminate\Http\Request;

class UserController extends Controller
{
    //
    public function index() 
    {
        return view('dashboard.pages.users.index', ['users' => User::orderBy('id', 'desc')->get()]);
    }

    public function create()
    {
        return view('dashboard.pages.users.create', ['roles' => Role::orderBy('id', 'desc')->get()]);
    }

    public function store(Request $request)
    {
        $data = $request->all();
        $data['password'] = bcrypt(123456);

        User::create($data);
       
        session()->flash('flash_message', 'User added Successfully!');

        return redirect()->route('users.index');
    }

}

resources/views/dashboard/pages/users/create.blade.php
@extends('dashboard.app')
@section('content')
<section class="content-header">
        <h1>
          Roles
          <small>Role for different users</small>
        </h1>
        <ol class="breadcrumb">
          <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
          <li><a href="{{ route('assets.index')}}">Roles</a></li>
          <li class="active">Add Role</li>
        </ol>
        </section>
<div class="col-md-10 col-md-offset-1">
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Add Role</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form method="POST" action="{{ route('users.store') }}">
            {{ csrf_field() }}

            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name" class="control-label">Name</label>
                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group">
                    <label for="role_id">Role</label>
                    <select class="form-control" name="role_id" id="role_id">
                        @foreach($roles as $role)
                            <option value="{{$role->id}}">{{ $role->name }}</option>
                        @endforeach
                    </select>
                </div>
            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                        <label for="email" class="control-label">E-Mail Address</label>
                    <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                    @if ($errors->has('email'))
                        <span class="help-block">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
                </div>
            


            <div class="form-group">
                <div class="">
                    <button type="submit" class="btn btn-sm btn-primary pull-right">
                        Register
                    </button>
                </div>
            </div>
        </form>
  </div>
</div>
  @endsection

resources/views/dashboard/pages/users/index.blade.php
@extends('dashboard.app')
@section('content')

        <!-- Content Header (Page header) -->
        <section class="content-header">
             <h1>
                Assets
                <small>List of all Roles</small>
             </h1>
        <ol class="breadcrumb">
          <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
          <li>Roles</li>
        </ol>
        </section>
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Roles</h3>
      <a href="{{ route('roles.create') }}" class="btn btn-sm btn-primary pull-right">Add Role</a>
    </div>
    <!-- /.box-header -->
    <table class="table table-hover datatable">
        <thead>
            <th>No</th>
            <th>Name</th>
            <th>Role</th>
        </thead>
        <tbody>
            @foreach($users as $key=>$user)
                <tr>
                    <td>{{ $key+1 }}</td>
                    <td>{{ ucwords($user->name) }}</td>
                    <td>{{ ucfirst($user->role->name) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
  </div>
  @endsection