routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('homepage');

//asset category route

Route::resource('categories', 'CategoryController');
//assets routes

Route::resource('assets', 'AssetController');
//roles routes

Route::resource('roles', 'RoleController');
//users routes

Route::resource('users', 'UserController');

resources/views/dashboard/pages/asset-category/create.blade.php
@extends('dashboard.app')
@section('content')
<section class="content-header">
        <h1>
          Asset Category
          <small>Categories for all the assets</small>
        </h1>
        <ol class="breadcrumb">
          <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
          <li><a href="{{ route('categories.index')}}">Categories</a></li>
          <li class="active">Add Category</li>
        </ol>
        </section>
<div class="col-md-10 col-md-offset-1">
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Add Asset Category</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form" action="{{ route('categories.store')}}" method="POST">
        {{ csrf_field() }}
      <div class="box-body">
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" class="form-control" id="name" name="name" placeholder="Enter name" required>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" name="description" id="description"></textarea>
        </div>
        <div class="checkbox">
          <label>
            <input type="checkbox" name="active" id="active" value="1"> Active
          </label>
        </div>
      </div>
      <!-- /.box-body -->

      <div class="box-footer">
        <button type="submit" class="btn btn-primary btn-sm pull-right">Save Asset Category</button>
      </div>
    </form>
  </div>
</div>
  @endsection

resources/views/dashboard/pages/asset-category/edit.blade.php
@extends('dashboard.app')
@section('content')
<section class="content-header">
        <h1>
          Asset Category
          <small>Categories for all the assets</small>
        </h1>
        <ol class="breadcrumb">
          <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
          <li><a href="{{ route('categories.index')}}">Categories</a></li>
          <li class="active">Edit Category</li>
        </ol>
        </section>
<div class="col-md-10 col-md-offset-1">
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Edit Asset Category</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form" action="{{ route('categories.update',$category->id)}}" method="POST">
        {{ csrf_field() }}
        {{ method_field('put') }}
      <div class="box-body">
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" class="form-control" id="name" name="name" value="{{$category->name }}" required>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" name="description" id="description">{{$category->description }}</textarea>
        </div>
        <div class="checkbox">
          <label>
            <input type="checkbox" name="active" id="active" value="1" {{ $category->active ? 'checked' : ''}}> Active
          </label>
        </div>
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
        <button type="submit" class="btn btn-primary btn-sm pull-right">Update Asset Category</button>
      </div>
    </form>
  </div>
</div>
  @endsection

resources/views/dashboard/pages/asset-category/index.blade.php
@extends('dashboard.app')
@section('content')

        <!-- Content Header (Page header) -->
        <section class="content-header">
             <h1>
                Assets
                <small>List of all asset categories</small>
             </h1>
        <ol class="breadcrumb">
          <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
          <li>Categories</li>
        </ol>
        </section>
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Asset Categories</h3>
      <a href="{{ route('categories.create') }}" class="btn btn-sm btn-primary pull-right">Add Category</a>
    </div>
    <!-- /.box-header -->
    <table class="table table-hover datatable">
        <thead>
            <th>No</th>
            <th>Name</th>
            <th>Description</th>
            <th>Active</th>
            <th>Action</th>
        </thead>
        <tbody>
            @foreach($categories as $key => $category)
            <tr>
                <td>{{ $key +1 }}</td>
                <td>{{ $category->name }}</td>
                <td>{{ substr($category->description,0,50) }}</td>
                <td>@if($category->active)<i class="fa fa-check"></i>@else <i class="fa fa-times"></i> @endif</td>
                <td>
                    <a href="{{ route('categories.edit',$category->id)}}" class="btn btn-sm btn-info"><i class="fa fa-edit"></i></a>
                    <a href="#" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
  </div>
  @endsection