routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('homepage');

//asset category route

Route::resource('categories', 'CategoryController');
//assets routes

Route::resource('assets', 'AssetController');
//roles routes

Route::resource('roles', 'RoleController');
//users routes

Route::resource('users', 'UserController');

resources/views/dashboard/partials/sidebar.blade.php
<!-- Sidebar user panel -->
<div class="user-panel">
  <div class="pull-left image">
    <i class="fa fa-user" style="color:orange; font-size:25px;"></i>
  </div>
</div>
<!-- sidebar menu: : style can be found in sidebar.less -->
<ul class="sidebar-menu" data-widget="tree">
  <li class="header">MAIN NAVIGATION</li>
  <li class="treeview">
    <a href="#">
      <i class="fa fa-dashboard"></i> <span>Assets</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li><a href="{{ route('categories.index') }}"><i class="fa fa-circle-o"></i>Categories</a></li>
      <li><a href="{{ route('assets.index') }}"><i class="fa fa-circle-o"></i>Assets</a></li>
    </ul>
  </li>
  <li class="treeview">
      <a href="#">
        <i class="fa fa-user-circle"></i> <span>Roles</span>
        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
      </a>
      <ul class="treeview-menu">
        <li><a href="{{ route('roles.index') }}"><i class="fa fa-circle-o"></i>Roles</a></li>
        <li><a href="{{ route('roles.create') }}"><i class="fa fa-circle-o"></i>Add Role</a></li>
      </ul>
    </li>
    <li class="treeview">
        <a href="#">
          <i class="fa fa-user-plus"></i> <span>Users</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="{{ route('users.index') }}"><i class="fa fa-circle-o"></i>Users</a></li>
          <li><a href="{{ route('users.create') }}"><i class="fa fa-circle-o"></i>Add User</a></li>
        </ul>
      </li>
</ul>
</section>
<!-- /.sidebar -->
</aside>

<!-- =============================================== -->

<!-- Content Wrapper. Contains page content -->