routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('homepage');

//asset category route

Route::resource('categories', 'CategoryController');
//assets routes

Route::resource('assets', 'AssetController');
//roles routes

Route::resource('roles', 'RoleController');
//users routes

Route::resource('users', 'UserController');

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    //
    protected $fillable = ['name', 'description', 'active'];

}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('dashboard.pages.roles.index', [ 'roles' => Role::orderBy('id', 'desc')->get() ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('dashboard.pages.roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = $request->all();
        $data['active'] = $request->get('active') ? 1 :0;

        Role::create($data);
        session()->flash('flash_message', 'Role added Successfully!');

        return redirect()->route('roles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        return view('dashboard.pages.roles.edit', ['role' => Role::findOrFail($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $data = $request->all();
        $data['active'] = $request->get('active') ? 1 : 0;
        Role::findOrFail($id)->update($data);
        session()->flash('flash_message', 'Role Updated Successfully!');

        return redirect()->route('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        //
    }
}

resources/views/dashboard/pages/roles/create.blade.php
@extends('dashboard.app')
@section('content')
<section class="content-header">
        <h1>
          Roles
          <small>Role for different users</small>
        </h1>
        <ol class="breadcrumb">
          <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
          <li><a href="{{ route('assets.index')}}">Roles</a></li>
          <li class="active">Add Role</li>
        </ol>
        </section>
<div class="col-md-10 col-md-offset-1">
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Add Role</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form" action="{{ route('roles.store')}}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
      <div class="box-body">
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" class="form-control" id="name" name="name" placeholder="Enter name" required>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" name="description" id="description"></textarea>
        </div>
        <div class="checkbox">
          <label>
            <input type="checkbox" name="active" id="active" value="1"> Active
          </label>
        </div>
      </div>
      <!-- /.box-body -->

      <div class="box-footer">
        <button type="submit" class="btn btn-primary btn-sm pull-right">Save Role</button>
      </div>
    </form>
  </div>
</div>
  @endsection

resources/views/dashboard/pages/roles/edit.blade.php
@extends('dashboard.app')
@section('content')
<section class="content-header">
        <h1>
          Roles
          <small>Role for different users</small>
        </h1>
        <ol class="breadcrumb">
          <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
          <li><a href="{{ route('assets.index')}}">Roles</a></li>
          <li class="active">Add Role</li>
        </ol>
        </section>
<div class="col-md-10 col-md-offset-1">
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Add Role</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form" action="{{ route('roles.update', $role->id)}}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('put')}}
      <div class="box-body">
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" class="form-control" id="name" name="name" value="{{ $role->name }}" required>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" name="description" id="description">{{ $role->description }}</textarea>
        </div>
        <div class="checkbox">
          <label>
            <input type="checkbox" name="active" id="active" value="1" {{ $role->active ? 'checked' : ''}}> Active
          </label>
        </div>
      </div>
      <!-- /.box-body -->

      <div class="box-footer">
        <button type="submit" class="btn btn-primary btn-sm pull-right">Update Role</button>
      </div>
    </form>
  </div>
</div>
  @endsection

resources/views/dashboard/pages/roles/index.blade.php
@extends('dashboard.app')
@section('content')

        <!-- Content Header (Page header) -->
        <section class="content-header">
             <h1>
                Assets
                <small>List of all Roles</small>
             </h1>
        <ol class="breadcrumb">
          <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
          <li>Roles</li>
        </ol>
        </section>
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Roles</h3>
      <a href="{{ route('roles.create') }}" class="btn btn-sm btn-primary pull-right">Add Role</a>
    </div>
    <!-- /.box-header -->
    <table class="table table-hover datatable">
        <thead>
            <th>No</th>
            <th>Name</th>
            <th>Description</th>
            <th>Active</th>
            <th>Action</th>
        </thead>
        <tbody>
            @foreach($roles as $key=>$role)
                <tr>
                    <td>{{ $key+1 }}</td>
                    <td>{{ $role->name }}</td>
                    <td>{{ substr($role->description, 0, 20) }}</td>
                    <td>@if($role->active)<i class="fa fa-check"></i>@else <i class="fa fa-times"></i> @endif</td>
                    <td>
                        <a href="{{ route('roles.edit',$role->id)}}" class="btn btn-sm btn-info"><i class="fa fa-edit"></i></a>
                        <a href="#" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
  </div>
  @endsection